### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/Palaeoanalytics#107]
We need to start writing the text for the JOSS submission. Here are the requirements:

- https://joss.readthedocs.io/en/latest/submitting.html

I have created a hackmd where we can start drafting the paper:

https://hackmd.io/AKH_L5lgRSSjsn3CTlBWAA

**Comment by JasonGellis** [comment]
generate a PDF on JOSS. https://whedon.theoj.org/
