### ISSUE TITLE
Drawing guidelines for pylithics

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/Palaeoanalytics#112]
Write some small guidelines of expected drawing style for pylithics to add to the readme.

**Comment by crangelsmith** [comment]
Hi @JasonGellis do you think we can have this for Friday before the JOSS submission? I think 2 sentences should suffice.

**Comment by JasonGellis** [comment]
@crangelsmith Absolutely. Working on it now.

**Comment by JasonGellis** [comment]
This is now posted on the README.md and in the JOSS paper
