### ISSUE TITLE
Running problems 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/Palaeoanalytics#117]
From develop

- [x] If output doesn't exist create a new output directory
- [x] Modify the tests for the newest openCV version (unpack 2 instead of 3)
- [x] Modify CI script to make sure is using right openCV
- [x] Run all tests

**Comment by crangelsmith** [comment]
Hi @JasonGellis , i think the issues that we were having this morning are now fixed (see PR #118 that now is merged into `develop`). 

Could you again do a clean run (from the `develop` branch) and let me know in this issue if everything works ok?

**Comment by JasonGellis** [comment]
@crangelsmith Camila, i have run this successfully from the `develop` branch. It work when I specify an existing output directory; and when there is no output directory, PyLithics generates one.
