### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by steko** [alan-turing-institute/Palaeoanalytics#135]
Regarding the review point "Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?" I see there is a testsuite that is linked to the Travis CI platform. The Travis YAML file is well organized.

I think it would add to the quality of the documentation if the test suite was mentioned, as part of a development/contributing section and not just the "badge" linking to Travis, since pytest can be run locally.

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice @steko This issue has been addressed and merged in to the main branch. https://github.com/alan-turing-institute/Palaeoanalytics/blob/c2bcb75995338c22f32f8690dff65e5bde68c3ae/README.md?plain=1#L240
