### ISSUE TITLE
Missing reference Moody2004

### ISSUE THREAD

**Issue by steko** [alan-turing-institute/Palaeoanalytics#136]
The reference **Moody2004** is missing from the bib file (the proof shows the citation key followed by "?").

**Comment by JasonGellis** [comment]
@steko @MichaelHoltonPrice please see corrections to the above on this branch: JOSS_corrections
https://github.com/alan-turing-institute/Palaeoanalytics/tree/JOSS_corrections

Once this is aproved by JOSS, I will merge into the main branch.

**Comment by JasonGellis** [comment]
@steko this issue has been corrected and merged into the main branch
