### ISSUE TITLE
Delete comma

### ISSUE THREAD

**Issue by MichaelHoltonPrice** [alan-turing-institute/Palaeoanalytics#137]
It's incredibly minor, of course, but the following commas do not belong:

"open-source, free for use, software" --> "open-source, free for use software"

"can identify and platform, lateral, dorsal," --> "can identify and platform lateral, dorsal,"

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice please see corrections to the above on this branch: JOSS_corrections
https://github.com/alan-turing-institute/Palaeoanalytics/tree/JOSS_corrections

Once this is aproved by JOSS, I will merge into the main branch.

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice this issue has been corrected and merged into the main branch

**Comment by MichaelHoltonPrice** [comment]
Looks good
