### ISSUE TITLE
Minor wording and punctuation issues (etc.)

### ISSUE THREAD

**Issue by MichaelHoltonPrice** [alan-turing-institute/Palaeoanalytics#138]
In addition to the preceding Issue to delete two commas, I will add all similar such things here.

(a)
Missing space:
"at a 1:1 scale,with" --> "at a 1:1 scale, with"

(b)
Use of the Oxford comma is inconsistent. Please adopt a convention and follow throughout. It's minor, of course, but I (for one) read more slowly when I don't know which convention applies.

For example, this sentence does not use the Oxford comma: "This tool accurately identifies, outlines and computes lithic shape and linear measures, and returns user ready data."

However, this one does: "Each aspect contains internal details (i.e., flake scars, cortical areas, etc.), indication of flaking direction radial lines (ripples), and the inclusion of a metric scale (for more information about lithic drawings see [@Martingell1988])."

(c)
In general, the list and figure are very helpful. The following numbered item is awkwardly phrased:
"1. Import images and match image name find to associated image ID and scale image from CSV meetadata file."

Also, it should be metadata, not meetadata

(d)

The following sentence needs a period after "fast moving".
"the develop branch contains the most up to date stable version of the code, but this branch is fast moving if you want to have a stable and static version is better to use main branch"

(e)
Change "correspond" to "corresponds" in the following sentence:
"An example of this table, where one scale correspond to several images is the following:"

(f)
Capitalize lithics at the beginning of the following sentence:
"lithics image files must still be inside the '<path_to_input_dir>/images/' directory)."

(g)
Missing to in the following sentence ("If you want use" --> "If you want to use"):
"If you want use PyLithics with different styles of drawing you might have to modify this configuration file."

(h)
"form" --> "from" in the following sentence:
"For each surface the metrics form its scars are recorded."

(i)
Reword the following sentence:
"In this data output example you can find the json file resulting of running PyLithics on the above images, with comments to better understand the hierarchy and variables."
-->
"In this data output example[,] you can find the json file [that results from] running PyLithics on the above images, with comments to better understand the hierarchy and variables."

(j)
Optionally, consider "cater to" rather than "cater for". Preposition choice is always fuzzy.

(k)
In the image, style guideline B) has a typo:
"Have arrow tails longer that arrow points" --> "Have arrow tails longer tha[n] arrow points"

(l)
"If you have ideas in how to" -> "If you have ideas [o]n how to"

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice please see corrections to the above on this branch: JOSS_corrections
https://github.com/alan-turing-institute/Palaeoanalytics/tree/JOSS_corrections

Once this is aproved by JOSS, I will merge into the main branch.

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice These issues have been corrected and merged into the main branch.
