### ISSUE TITLE
@JasonGellis the README and the Travis configuration file still have a mix of pip and conda. Everything works, but I think it makes the installation process more fragile.

### ISSUE THREAD

**Issue by MichaelHoltonPrice** [alan-turing-institute/Palaeoanalytics#139]
I noticed the same thing. I am creating a new issue to make sure this is addressed. Both the main and develop branches still mention conda.

@JasonGellis the README and the Travis configuration file still have a mix of pip and conda. Everything works, but I think it makes the installation process more fragile.

_Originally posted by @steko in https://github.com/alan-turing-institute/Palaeoanalytics/issues/130#issuecomment-932872664_

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice Thank you for clarifying. I'll get right on it (and the remaining isssues).

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice please see the updated installation instructions on this branch: joss_paper/139_native_install
[](https://github.com/alan-turing-institute/Palaeoanalytics/tree/joss_paper/139_native_install)

Once this is aproved by JOSS, I will merge into the main branch.

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice the README and travis files have been updated for native install and merged into main.

**Comment by MichaelHoltonPrice** [comment]
Looks good. Thank you! I have opened a new issue regarding Windows syntax, though it is a minor thing.
