### ISSUE TITLE
setup.py undocumented

### ISSUE THREAD

**Issue by MichaelHoltonPrice** [alan-turing-institute/Palaeoanalytics#140]
There is a setup.py file, but its usage is not documented in the README.

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice this has been addressed and merged int the main branch. https://github.com/alan-turing-institute/Palaeoanalytics/blob/e11e1f4f30badb4079dbe40488fdfb033a9de512/README.md?plain=1#L94

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice this issue has now been merged to the main branch. Can you please advise on the next step?
