### ISSUE TITLE
Incomplete test coverage

### ISSUE THREAD

**Issue by MichaelHoltonPrice** [alan-turing-institute/Palaeoanalytics#168]
First off, my heartiest commendation on a remarkable piece of work. It is at the >99% level in code framework and maturity compared to the many archaeological code bases I interact with, including in its use of tests. I believe your tests are easily sufficient to demonstrate that the code is working as it should, and I will be marking the corresponding item in review to indicate so momentarily.

Nevertheless, it seems worth documenting that the test coverage is not quite complete. In particular (and if I have not made any mistakes), there are no tests for template_matching, data_output, associate_arrows_to_scar, or any of the methods in plotting.py.

**Comment by JasonGellis** [comment]
@MichaelHoltonPrice Test coverage documentation has been completed. I think there might me some confusion on this. We use the the pytest library. All that's needed is to go to the main Palaeoanalytics directory and type `pytest -s`

I have added a testing section section - Functional testing of PyLithics - in the REAME.md
